export const PokemonTypes = [
	{ label: "Normal", id: "normal" },
	{ label: "Fuego", id: "fire" },
	{ label: "Agua", id: "water" },
	{ label: "Eléctrico", id: "electric" },
	{ label: "Planta", id: "grass" },
	{ label: "Hielo", id: "ice" },
	{ label: "Lucha", id: "fighting" },
	{ label: "Veneno", id: "poison" },
	{ label: "Tierra", id: "ground" },
	{ label: "Volador", id: "flying" },
	{ label: "Psíquico", id: "psychic" },
	{ label: "Bicho", id: "bug" },
	{ label: "Roca", id: "rock" },
	{ label: "Fantasma", id: "ghost" },
	{ label: "Dragón", id: "dragon" },
	{ label: "Siniestro", id: "dark" },
	{ label: "Acero", id: "steel" },
	{ label: "Hada", id: "fairy" },
];
